### PR TITLE
Kodi logo

### PR DESCRIPTION
**Pull request by accumulator**

### CODE REVIEW

**Comment by RobertMe** [comment]
:+1: I would have hated it if I had to create them :smiley: 

@mzanetti Ok by me, but final verdict is of course on you. And I don't now about the legal side of things. I think one of the main reasons to change the name XBMC to Kodi was legal related, to better protect the name and artwork/logos. So I don't know if it's ok to copy/paste the logo into our logo.

**Comment by mzanetti** [comment]
love it. two things:

* Can you re-add that slight drop-shadow that the old logo had?
* Plase also update the ubuntu one

**Comment by accumulator** [comment]
I actually like it without the drop shadow. The kodi logo itself is fuzzy around the edges, so I think it's fitting this way

**Comment by accumulator** [comment]
And legally speaking, it's better to ask for forgiveness than for permission ;)

**Comment by RobertMe** [comment]
I think without shadows is indeed better.

**Comment by mzanetti** [comment]
ok. without shadows it is. Can you still update the the Ubuntu one pease?

**Comment by accumulator** [comment]
sure, will do this weekend

**Comment by RobertMe** [comment]
@accumulator is this ok now?

I don't think GitHub sends notifications on new commits, so you might want to add a comment when you've updated the branch/PR.

**Comment by nk8193308-crypto** [comment]
> _ No description provided. _

**Pull request merged**
