### PR TITLE
Add playlist support

### LINKED ISSUE #62: Normal/smart/stream playlist support
Please add support for playback of normal, smart and stream (music) playlists, in normal play and in party mode. (Maybe also add party mode in general?)

I usually use smart playlist to contain a subset of my music collection so that the party mode will not play all songs (such as livesets or long mixed album tracks).

I recall that when this features was implemented in the AWXi interface two years ago, there were issues with the API to get the playlists and differentiate between the types (stream file, playlist, smartl playlist) as I believe they were seen as some kind of virtual folders.  Possible this has been resolved, otherwise this feature might be blocked by a proper API?

### PR DESCRIPTION
**Pull request by RobertMe**
Add support for browsing both audio and video playlists. Fixes #62 

@paulvt What should party mode do? As far as I can see we can only set a player in "party mode" (Player.SetPartyMode, which takes an on/off value), which means we can only add it as another toggle next to shuffle and repeat. After some quick investigation it seems like we can't just get the "party mode playlist" from Kodi. As you said in your original issue, playlists are implemented as virtual folders (`special://musicplaylists` and `special://videoplaylists`), but the party mode playlist isn't returned as sub directory/file in those folders.

### CODE REVIEW

**Comment by paulvt** [comment]
I am basically confused by how it actually works because all skins implement it differently.
Normal skins have indeed the toggle, but toggling just means take 10 random tracks, play the first and once played, pop the first from the playlist and add it with another one... (or more if some tracks have been deleted in the meantime).  Some skin don't have a toggle but just Party Mode, which takes indeed the special list and plays that in that mode... stopping just stops party mode as well.
And I know that in most skins in the context menu of a playlist is: Play in party mode.. so indeed then it's a way of playing the list next to normal/shuffle/repeat/random.

I find the toggle very confusing as setting it to enable starts party mode, but setting it to off seems to just make Kodi stop adding tracks when a track is finished/removed and that's it (?).

**Comment by mzanetti** [comment]
@paulvt Basic playlist support will be in the next release (as you can see this branch is merged). We'll look into the party mode things in the future as it seems to be a bit more complicated.

**Comment by paulvt** [comment]
Great, I will try it out.  Webradio stations are also basic playlists, so that would be neat to have.

**Comment by RobertMe** [comment]
Not sure if that would work. We're currently gonna finalize the upcoming release, so you should be able to test it in a couple of days (probably after the weekend, unless some serious issue comes up). So please report back if it doesn't work then and we can look into it.

Or if you want to you can also send me an email (email address is shown in the about dialog), or join #kodimote on IRC (freenode), and I'll send you a beta/RC RPM (IIRC you were using Sailfish, right?) which you could use to test if at least the basic functionality works (and if webradio would be an easy fix if it doesn't work it might then still be in the final).

**Comment by paulvt** [comment]
Confirmed that radio stations that are put in the music playlist folder work.  Maybe the '.strm' extension still needs to be removed?

**Pull request merged**
