### PR TITLE
libkodimote: fixed duplicates during discovery when building WOL packet

### PR DESCRIPTION
**Pull request by tempura-san**

### CODE REVIEW

**Comment by mzanetti** [comment]
thanks!

**Comment by RobertMe** [comment]
Would this fix the issue @paulvt reported (in IRC) of hosts being added multiple times?

As I'm not sure of the relation between (duplicates) in host discovery and WOL. My guess would be that the `m_hwAddr.remove` call modifies the member var and thus during discovery it doesn't match the found MAC with the existing hosts MAC as one is with `:` and one without? (and by first assigning `m_hwAddr` to a new var the string gets copied and the `remove` call would thus modify the copy, not the member)

**Comment by tempura-san** [comment]
@mzanetti You're welcome. :)
@RobertMe I guess there was a misunderstanding in how QString.remove() works - it does not return a copy of the string with the ':' removed, but instead will alter the string in place.
I am not sure, but I think Python's string operations would work like the first example if I remember correctly.

**Comment by RobertMe** [comment]
That's what I thought. Most languages indeed return a new, modified, string and leave the original one as is. So my guess of what happened (and relation between discovery and WOL) was correct then.

So this should most likely indeed fix the issue reported by @paulvt, as IIRC he had one host were the MAC included the `:` and one without the `:`. So thanks for fixing from me too :)

**Pull request merged**
