### PR TITLE
Update minimum XBMC/Kodi version to Kodi Helix (v14)

### PR DESCRIPTION
**Pull request by RobertMe**
Build on top of #2 as that moves the version check.

### CODE REVIEW

**Comment by RobertMe** [comment]
We might need to rethink if we want to block access to older versions, as currently is the case.

We might be better of giving the user an information message that updating XBMC/Kodi is advised, and some functionality might not work. The same as we should possibly do for Xbmcremote, giving the user a hint to use Kodimote when connecting to Kodi Helix. When we don't allow connecting to XBMC users which still use both (on different systems) are also required to use both of the apps. While at least for now we still only use API functionality which is also present in Gotham, and most likely even Frodo. So right now Kodimote is still 100% compatible with Gotham (implementing #6 will make this 99% compatible), and probably 90%+ compatible with Frodo (only PVR and profile (#3) support aren't present in Frodo I think)

**Comment by accumulator** [comment]
Why is this check not done on API version? The Kodi developers have stated that Kodi v14 will not have an incompatible API change. This way you take away flexibility and burden the user with an upgrade that's not needed until probably Kodi v15/API v8

**Comment by RobertMe** [comment]
That's what I meant in my comment. This change forces the user to update, but it's a lot better to advice them to update, but allow all v6 API versions (so Frodo and up). Some things might be broken (like #6 when it gets implemented*), but it's not like the app is useless when you're using an older version of XBMC/Kodi.

* As stated in the issue this feature is currently already supported. So it _is_ possible to keep it working in Gotham (in Frodo there wasn't even PVR support), but we already decided to drop old code/versions. So I don't think there is any change that we keep both code paths, one for Gotham, and one for Helix and up.

**Comment by accumulator** [comment]
Hmm, so v6 API isn't so stable after all.. :)

Well we can make a branch for xbmcremote-up-to-gotham (which is currenty probably  equivalent to a tag), and keep that in low-maintenance for a while. At least until Kodi v14 is the majority out there.

I saw the mDNS name of Kodi is still using 'xbmc' in its identifier string, but *if* this changes to 'kodi' we could still support that in the branch for Kodi v14 (and in master, for that matter)

**Comment by RobertMe** [comment]
API v6 is stable, and backwards compatible. But new methods etc are still being added. So at some point we have to decide to drop support for older API versions. AFAIK API v7 will only come when they fully replace the JSON-RPC API with something else, or have a bunch of backwards incompatible changes lined up. Which both probably won't happen in the upcoming years.

So everything that works with the API of Frodo should still work with Helix' API, but the API of Helix contains more than Frodo (like PVR and profile switching). So features which are only possible due to the extended API of Helix obviously won't work with Frodo (and Gotham).

AFAIK the current plan of @mzanetti is to make one last Xbmcremote release (still on Gitorious), with the crash fix ( #15 ) and a note (but not forcing) to use Kodimote when connecting to a Kodi instance. So those who still use XBMC can keep using Xbmcremote, but those who are running Kodi can use Kodimote and will have all the new features.
If we set a hard limit on Kodimote to use Kodi is still a bit unclear. Best would be to notify users that some features are broken because they're using XBMC, but still allow them to connect and use the basic functionality.

We also have no plans to further support Xbmcremote (/older Kodi releases). New features are added to Kodimote and aren't backported. The only exception being the crash fix and the notice to upgrade to Kodimote. This so it allows us to not put any time in still supporting the older versions (which we both don't run), or older apps (the Maemo and MeeGo apps also haven't had any update in a long time).

At least for me there aren't enough (complaining) users to keep an extra XBMC install next to my Kodi install, and the same goes for still supporting MeeGo. My Nokia N9 is somewhere in a box and there has to be a pretty good reason to still use/develop for it. But if you (or someone else) wants to maintain a version for older XBMC releases, or other devices/platforms, you are of course free to do so.

**Comment by accumulator** [comment]
Thanks for describing the detailed state of affairs. 

I'm thinking about taking up the maintaince of xbmcremote for Harmattan and Sailfish, supporting v6 API and feature-set of Gotham. And where possible compatibility for Kodi v14. 

This should at least ease the transition to Kodimote, if there will be incompatibilities down the line..

**Comment by mzanetti** [comment]
Hey ya, yes, pretty much everything Robert said is correct (except I'm not actively looking after the KDE plasmoid any more).

Apologies for breaking your branches with the rename, as Robert said, it was an accidental push and as I assumed Robert and me were the only people working on it I didn't bother with reverting. Will be more careful now that I know our team is bigger.

It's great if you wanna take over the Harmattan port. Not sure about the state of the Nokia store, afaik it is down, but in any case, I can still publish packages on the website (If you want you can also upload it to that 3rd party store for meego which I've forgotten the name of).

Please consider stopping by the IRC channel #kodimote on freenode to talk about your plans and upcoming branches.

**Comment by RobertMe** [comment]
As agreed on IRC, we will try to make code as backwards compatible as possible.

**Comment by accumulator** [comment]
I've setup a https://github.com/accumulator/kodimote/tree/xbmcremote-maintenance branch from where we can make xbmcremote releases. I plan to collect (backported) fixes here for both harmattan and sailfish, with the Gotham featureset in mind. Kodi support is best-effort.

**Comment by RobertMe** [comment]
That wouldn't be needed, as we've decided that Kodimote will still support Gotham (that's what I meant with keeping the code backwards compatible).

And if you want to maintain the Harmattan version I'm sure @mzanetti won't remove it from the repo. And thus you can contribute to this repo.

**Comment by accumulator** [comment]
I understand. The idea for the maintenance branch is then just for a (final?) release of the client before the rename, so we can put a message in that recommends to install kodimote

**Comment by RobertMe** [comment]
We'll probably use the Gitorious repo for it. I think that was Michaels plan, to reset it to the latest release and then apply the changes for the last ever release.

**Pull request closed without merging**
