### PR TITLE
enable live volume update in ubuntu, prevent flooding from sailfish

### PR DESCRIPTION
**Pull request by mzanetti**

### CODE REVIEW

**Comment by RobertMe** [comment]
It does work in Sailfish also, but although this solution is a lot cleaner then #26, it still wouldn't fix the issue where it takes longer than the 100ms timeout to receive Kodis response. And besides it wouldn't fix the issue were the `Application.OnVolumeChanged` notification wouldn't be received, as reported by @accumulator .

Fixing the first issue could be done by disabling the binding I think (so setting the bindings `active` to `!down` (/`!pressed`). Fixing the second would require using the `Application.SetVolume` response, as that would contain the right value and should always be received (although it would be strange if the notification is not always received)

**Comment by mzanetti** [comment]
I don't think it happens often that it takes more than 100ms, if if that happens because of some temporary hickup, it recovers soon, given that the average ping time here in my wifi is in average 6.5 ms.

The second one isn't an issue with this solution as we don't care about the notification, so we also don't need to workaround the case when it doesn't show up.

**Comment by accumulator** [comment]
I'm sad to see this alternative is merged to master without any further debate.

**Comment by mzanetti** [comment]
You said you don't wanna waste any more time on it :)

Seriously, "let's just copy/paste this to all apps and be done with it" is not how it works. In order to keep the code maintainable and the app's quality high, changes need to work for all platforms. If it's something that's more complex, like real flow control as you did it, it really should go into the c++ part in order to not have to maintain the same "complex" code multiple times.

**Comment by accumulator** [comment]
I agree copypasting the QML is not ideal, and a C++ implementation is more proper, but I don't understand why you then ram through an equally copypasted semi-solution anyway?

**Comment by mzanetti** [comment]
It's really not the same thing. One tiny timer versus a flow control implementation...

That said, if you think it's worth it, we/you can still come up with the proper solution and implement the real flow control in libxbmc, probably in a new class called VolumeController that is instantiated from kodi.cpp. From your other comments it really didn't look like you'd want to do that. So I've added this fix, which to solve the issue.

**Comment by accumulator** [comment]
I'm not sure if I want to invest a lot of time in this project if decisions are made in this way.

**Comment by RobertMe** [comment]
While I agree with @accumulator  that "just replacing and merging" this PR isn't the way to go, the current implementation is better. We can't do the same in C++, using a timer etc, as it would also affect some other scenarios (like the volume "animation" when receiving a phone call, and the button presses).

And the current solution is correct enough (although I would still have preferred a C++ solution) to work for these apps and scenarios, and doesn't involve too much/complex code (while I had to take a good look at the code of #26 to understand what was actually going on and what you tried to fix).

> The second one isn't an issue with this solution as we don't care about the notification, so we also don't need to workaround the case when it doesn't show up.
This isn't true, as we only update the volume property (/`m_volume`) on the notification, so when you call `setVolume` the volume isn't updated immediately, but only when the notification gets received. So when we don't receive the notification we still have the old volume set.

And right now I'm also wondering if we shouldn't also set the volume immediately when you do the press, as the volume can be at 100%, and then you press at about 50% and still want to make some adjustments. In this case it would first take the 100ms before the first volume change is sent to Kodi. So the `if (!down)` / `if(!pressed)` condition should probably be dropped.

**Pull request merged**
